# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: Maven@3
  inputs:
    mavenPomFile: 'MyPhoenixApp/pom.xml'
    mavenOptions: '-Xmx3072m'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.8'
    jdkArchitectureOption: 'x64'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    goals: 'package'

- script: |
    # Save the entire job logs to a file
    echo "##### ArtifactStagingDirectory #####"
    ls -ltr $(Build.ArtifactStagingDirectory)
    echo "##### BuildDirectory #####"
    ls -ltr $(Agent.BuildDirectory)
    echo "##### BuildId #####"
    ls -ltr $(Build.BuildId)
  displayName: 'Save Job Logs'